steps:


  # Executa a tarefa como um Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - '${_SERVICE_NAME}-job' # É uma boa prática nomear como um job
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--set-env-vars' # O comando para variáveis de ambiente muda um pouco
      - 'GCP_PROJECT_ID=${PROJECT_ID},BQ_DATASET_ID=${_BQ_DATASET_ID},BQ_TABLE_ID=${_BQ_TABLE_ID}'
      - '--wait' # Espera o job terminar antes de finalizar o passo
      - '--service-account' # Especifica a conta de serviço para o job
      - 'sa-cloud-build-pipeline@${PROJECT_ID}.iam.gserviceaccount.com'

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'pipeline-paises'
  _REPOSITORY: 'pipelines'
  _BQ_DATASET_ID: 'portfolio_dados'
  _BQ_TABLE_ID: 'paises'

options:
  logging: CLOUD_LOGGING_ONLY