steps:
  # 1. Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}', '.']

  # 2. Envia a imagem construída para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to Artifact Registry'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}']

  # 3. Faz o deploy do Cloud Run Job (Cria na 1ª vez, atualiza nas seguintes)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: 'Deploy Job'
    args:
      - 'beta'  # <<< INFORMA QUE VAMOS USAR UM COMANDO BETA
      - 'run'
      - 'jobs'
      - 'deploy' # <<< COMANDO CORRETO AGORA
      - '${_SERVICE_NAME}-job'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--service-account'
      - 'sa-cloud-build-pipeline@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=${PROJECT_ID},BQ_DATASET_ID=${_BQ_DATASET_ID},BQ_TABLE_ID=${_BQ_TABLE_ID}'

  # 4. Executa o Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: 'Execute Job'
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - '${_SERVICE_NAME}-job'
      - '--region'
      - '${_REGION}'
      - '--wait'

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'pipeline-paises'
  _REPOSITORY: 'pipelines'
  _BQ_DATASET_ID: 'portfolio_dados'
  _BQ_TABLE_ID: 'paises'

options:
  logging: CLOUD_LOGGING_ONLY
